name: Publish to Maven Central

on:
  push:
    branches:
      - main    # 仅当推送到 main 分支时触发
    tags:
      - 'v*'    # 只匹配版本号标签，例如 v1.0.0、v2.1.0 等
      - 'release-*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: release-env

    steps:
      - name: Set up Node.js 20  # 使用 Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Set up GPG
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "default-cache-ttl 600" >> ~/.gnupg/gpg-agent.conf
          echo "max-cache-ttl 7200" >> ~/.gnupg/gpg-agent.conf
          echo RELOADAGENT | gpg-connect-agent

      - name: Copy settings.xml to .m2
        run: cp ./.github/workflows/settings.xml ~/.m2/settings.xml

      - name: Publish to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mvn -U -B clean deploy -P release -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
